// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyOun3coSVWHPm0uKgxa5Bel7sm5PQqvU',
    appId: '1:728899691566:web:2ca1dc64566a8aa690abbf',
    messagingSenderId: '728899691566',
    projectId: 'projectquizzapp',
    authDomain: 'projectquizzapp.firebaseapp.com',
    storageBucket: 'projectquizzapp.appspot.com',
    measurementId: 'G-HB0NVJ0SJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_neMmCSVGkTUF6kNNWYaC95kEzJMv_rM',
    appId: '1:728899691566:android:e38fb07c0acea1ef90abbf',
    messagingSenderId: '728899691566',
    projectId: 'projectquizzapp',
    storageBucket: 'projectquizzapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3BXb5Wx3_MD2Eh37g1_fhxq0Tq_sQCss',
    appId: '1:728899691566:ios:e22085b3dbd06f8190abbf',
    messagingSenderId: '728899691566',
    projectId: 'projectquizzapp',
    storageBucket: 'projectquizzapp.appspot.com',
    iosClientId: '728899691566-96mst2kn7ts5a0u0g6uuprioiqhk4t74.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3BXb5Wx3_MD2Eh37g1_fhxq0Tq_sQCss',
    appId: '1:728899691566:ios:e22085b3dbd06f8190abbf',
    messagingSenderId: '728899691566',
    projectId: 'projectquizzapp',
    storageBucket: 'projectquizzapp.appspot.com',
    iosClientId: '728899691566-96mst2kn7ts5a0u0g6uuprioiqhk4t74.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterQuizApp',
  );
}
